#токен бота
bot_token: 682:iwTY
#ID чата получателя
chat_id: -403
#чат для сервисных сообщений, если пустой, используется значение предыдущего параметра
service_chat_id: -400
#ID пользователя, от которого принимаются команды
user_id: 418
#Один бот для всех станций
one_bot_4all: true
#включить команды управления ботом
command_on: true
#вывод имени ПК в сообщениях
view_hostname: false

#onlineIpInfo может принимать значение только false или true. false - инфо по IP используя оффлайн базу GeoLite, true - инфо по IP через сайт ipinfo.io
online_ip_info: true
#автообновление файлов GeoLite с Github
auto_update_geolite: true

#Проверять свободное место на дисках
check_free_space: true
#Проверять наличие файлов EasyAntiCheat.exe и EasyAntiCheat_EOS.exe
check_anticheat: true
#Мониторить температуры
check_temp_on: true
#порог проверки работы вентиляторов видеокарты
fan_t: 75
#минимальные обороты при FANt
fan_rpm: 900
#порог температуры процессора
cpu_tmax: 85
#порог температуры ядра видеокарты
gpu_tmax: 85
#порог температуры HotSpot видеокарты
gpu_hs_tmax: 90
#Дельта температуры
delta_t: 5

#Блокировка "хитрых" триальщиков. false - нет блокировки
trial_block: true
#сбор статистики по триальщикам в trial.txt. false - не собирается статистика в trial.txt
trial_on: true
#Файл с триальщиками
trial_file_lan: trial.txt

#включение сообщений при начале сессии. false - сообщение не будет приходить
start_message_on: true
#включение о сообщении об окончании сессии. false - сообщение не будет приходить
stop_message_on: true
#оповещать о сессиях менее Х минут, выставлять в config.go. false - сообщение не будет приходить
short_session_on: true
#Минимальное время сессии в минутах, при котором отправляется сообщение
min_minute: 10
#сообщение с комментарием клиента. false - сообщение не будет приходить
comment_message_on: true
